[package]
name = "ReflexionFinder"
version = "1.0.0"
edition = "2024"
author = "shoxxdj"

[dependencies]
url = "2"
reqwest = { version = "0.11", features = ["blocking", "socks", "default-tls"] }
clap = { version = "4.5.1", features = ["derive"] }
rand = "0.8"
